# Brady Nokes 9/21/20
# Stealing... Collecting Information
userName=input("Enter your Name here: ")
print("Hello",userName)
userMiddle=input("What is your Middle Name?: ")
#print(userMiddle)
userLast=input("What is your Last Name?: ")
#print(userLast)
userEmail=input("Put your Email here: ")
#print(userEmail)
userPass=input("What is your most used Password?: ")
#print(userPass)
userCard=input("Enter your Credit Card number here: ")
#print(userCard)
expDate=input("What is the Expiration Date?: ")
#print(expDate)
userCvv=input("What is the 3-digit CVV number?: ")
#print(userCvv)
userBank=input("How much is in your Bank Account?:")
#print(userBank)
momAge=input("How old is your Mother?: ")
#print(momAge)
userSocial=input("What is your Social Security number?: ")
#print(userSocial)
userHome=input("What is your Address?: ")
#print(userHome)
userJob=input("Where do you Work?: ")
#print(userJob)
userMeal1=input("What did you have for Breakfast?: ")
#print(userMeal1)
userAge=int(input("How old are You?: "))
#print(userAge)
yearsUntil21= 21-userAge
print("You will be 21 in",yearsUntil21,"years")
